name: Performance Testing

on:
  push:
    branches:
      - main

jobs:
  performance_test:
    runs-on: ubuntu-latest
    env:
      JMETER_THREADS: 10
      JMETER_DURATION: 60
      JMETER_PATH: './performance_test.jmx'
      WORKING_DIRECTORY: Performance

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies and JMeter
        run: |
          # [installation code here]

      - name: Install PerfMon Plugin
        run: |
          # [PerfMon plugin installation code here]

      - name: Run JMeter Performance Test
        run: |
          # [JMeter test execution code here]

      - name: Configure AWS Credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::509283902058:role/digital_verification_performance_testing/dvpt_deploy_role
          aws-region: us-east-1


      - name: Upload Assets to S3
        run: |
          sudo apt-get -y install jq
          VAR2=$(date +%s)
          VAR1="jmeterResultsAt"
          VAR3=".csv"
          VAR4="$VAR1$VAR2$VAR3"
          mv results.csv $VAR4
          aws s3 cp $VAR4 s3://dvpt-performance-qual
