name: PR Verify

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JMeter
        run: |
          docker run --rm \
            -e client_id=${{ secrets.CLIENT_ID_JMETER }} \
            -e client_secret=${{ secrets.CLIENT_SECRET_JMETER }} \
            -v ${{ github.workspace }}:/jmeter \
            justb4/jmeter \
            jmeter -n -Jclient_id_jmeter=${{ secrets.CLIENT_ID_JMETER }} -Jclient_secret_jmeter=${{ secrets.CLIENT_SECRET_JMETER }} -t /jmeter/performance_test.jmx -l /jmeter/results.csv

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Upload assets to S3
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          VAR2=$(date +%s)
          VAR1="jmeterResultsAt"
          VAR3=".csv"
          VAR4="$VAR1$VAR2$VAR3"
          mv results.csv $VAR4
          aws s3 cp $VAR4 s3://dvpt-performance-qual --region ap-southeast-1 --delete
